## Q4

In [1]:
import numpy as np
import pandas as pd
from scipy.stats import norm

df = pd.read_csv('./data/ames_prices.csv')
x = (df['Central.Air'] == 'Y').astype(int)
n = len(x)
p_hat = x.mean()
print(f'n = {n}, p_hat = {p_hat:.4f}')

n = 2930, p_hat = 0.9331

In [2]:
np.random.seed(1)
R = 2_000
results = []
for t in range(R):
    idx = np.random.randint(0, n, n)
    results.append(x.iloc[idx].mean())
results = np.array(results)
print(f'seed = 1, R = {R}')

seed = 1, R = 2000

In [3]:
p_0 = .90
se = np.std(results, ddof=1)
z = (p_hat - p_0) / se
p = 2 * norm.cdf(-np.abs(z))
row = {'variable': 'Central.Air', 'estimate': p_hat, 'SE': se, 'z': z, 'p': p}
for conf, alpha in [(90, .10), (95, .05), (99, .01)]:
    c = norm.ppf(1 - alpha / 2)
    row[f'normal {conf}%'] = f'({p_hat - c*se:.4f}, {p_hat + c*se:.4f})'
    row[f'contains p_0 {conf}%'] = p_hat - c*se <= p_0 <= p_hat + c*se
row['significant at'] = ', '.join(f'{conf}%' for conf, alpha in [(90, .10), (95, .05), (99, .01)] if p < alpha) or 'none'

ci_table = pd.DataFrame([row]).set_index('variable')
ci_table.round(3)

,estimate,SE,z,p,normal 90%,contains p_0 90%,normal 95%,contains p_0 95%,normal 99%,contains p_0 99%,significant at
variable,,,,,,,,,,,
Central.Air,0.933,0.005,7.123,0.0,"(0.9255, 0.9408)",False,"(0.9240, 0.9422)",False,"(0.9211, 0.9451)",False,"90%, 95%, 99%"

About 93.3% of homes in the sample have central air. The 95% CI is (92.4, 94.2), so the true proportion is probably in that range. 0.90 is outside all three intervals and p is approx 0, so we reject $H_0$ at 90, 95, and 99%. The share of ames homes with central air is higher than 90%.

## Q5

In [4]:
x = np.arcsinh(df['area'])
y = np.arcsinh(df['price'])
n = len(df)
rho_hat = np.corrcoef(x, y)[0, 1]
print(f'n = {n}, rho_hat = {rho_hat:.4f}')

n = 2930, rho_hat = 0.7232

In [5]:
np.random.seed(1)
R = 2_000
results = []
for t in range(R):
    idx = np.random.randint(0, n, n)
    results.append(np.corrcoef(x.iloc[idx], y.iloc[idx])[0, 1])
results = np.array(results)
print(f'seed = 1, R = {R}')

seed = 1, R = 2000

In [6]:
rho_0 = 0
se = np.std(results, ddof=1)
z = (rho_hat - rho_0) / se
p = 2 * norm.cdf(-np.abs(z))
row = {'variable': 'corr(area, price)', 'estimate': rho_hat, 'SE': se, 'z': z, 'p': p}
for conf, alpha in [(90, .10), (95, .05), (99, .01)]:
    c = norm.ppf(1 - alpha / 2)
    row[f'normal {conf}%'] = f'({rho_hat - c*se:.4f}, {rho_hat + c*se:.4f})'
    row[f'contains rho_0 {conf}%'] = rho_hat - c*se <= rho_0 <= rho_hat + c*se
row['significant at'] = ', '.join(f'{conf}%' for conf, alpha in [(90, .10), (95, .05), (99, .01)] if p < alpha) or 'none'

ci_table = pd.DataFrame([row]).set_index('variable')
ci_table.round(3)

,estimate,SE,z,p,normal 90%,contains rho_0 90%,normal 95%,contains rho_0 95%,normal 99%,contains rho_0 99%,significant at
variable,,,,,,,,,,,
"corr(area, price)",0.723,0.01,69.188,0.0,"(0.7060, 0.7404)",False,"(0.7027, 0.7437)",False,"(0.6962, 0.7501)",False,"90%, 95%, 99%"

The correlation between arcinh of area and price is 0.723, so bigger houses tend to sell for more. 0 is not included in all three intervals and p is close to 0, so we reject $H_0$ at 90, 95, and 99%. 

If area and price were resample separately, each house's area would pair with a other random house's price, so we don't see a real relationship, and every bootstrap correlation would be close to 0. The standard error and CIs would not describe a real relationship.

## Q6

In [7]:
df = pd.read_csv('./data/metabric.csv')
x = df['Overall Survival (Months)']
n = len(x)
mu_hat = x.mean()
print(f'n = {n}, mu_hat = {mu_hat:.4f}')

n = 1343, mu_hat = 129.0943

In [8]:
np.random.seed(1)
R = 2_000
results = []
for t in range(R):
    idx = np.random.randint(0, n, n)
    results.append(x.iloc[idx].mean())
results = np.array(results)
print(f'seed = 1, R = {R}')

seed = 1, R = 2000

In [10]:
mu_0 = 120
se = np.std(results, ddof=1)
z = (mu_hat - mu_0) / se
p = 2 * norm.cdf(-np.abs(z))
row = {'variable': 'overall Survival (Months)', 'estimate': mu_hat, 'SE': se, 'z': z, 'p': p}
for conf, alpha in [(90, .10), (95, .05), (99, .01)]:
    c = norm.ppf(1 - alpha / 2)
    row[f'normal {conf}%'] = f'({mu_hat - c*se:.2f}, {mu_hat + c*se:.2f})'
    row[f'normal {conf}% (years)'] = f'({(mu_hat - c*se)/12:.2f}, {(mu_hat + c*se)/12:.2f})'
    row[f'contains mu_0 {conf}%'] = mu_hat - c*se <= mu_0 <= mu_hat + c*se
row['significant at'] = ', '.join(f'{conf}%' for conf, alpha in [(90, .10), (95, .05), (99, .01)] if p < alpha) or 'none'

ci_table = pd.DataFrame([row]).set_index('variable')
ci_table.round(3)

,estimate,SE,z,p,normal 90%,normal 90% (years),contains mu_0 90%,normal 95%,normal 95% (years),contains mu_0 95%,normal 99%,normal 99% (years),contains mu_0 99%,significant at
variable,,,,,,,,,,,,,,
overall Survival (Months),129.094,2.186,4.159,0.0,"(125.50, 132.69)","(10.46, 11.06)",False,"(124.81, 133.38)","(10.40, 11.11)",False,"(123.46, 134.73)","(10.29, 11.23)",False,"90%, 95%, 99%"

The mean recorded time is 129.1 months. 120 months is excluded in all three intervals and $p$ is close to $0$, so we reject $H_0$ at 90, 95, and 99%. The mean recorded time is longer than 10 years.

This is not the average lifetime after diagnosis. 576 of the 1343 were still living, so each time is how long they were followed, not until they died. Their survival times are longer than recorded, so the true mean lifetime is be higher than our estimate.

## Q7

In [11]:
df = pd.read_csv('./data/nhanes_data_17_18.csv', low_memory=False)
sdf = df.loc[(df['AgeInYearsAtScreening'] >= 18) & df['SleepHoursWeekdaysOrWorkdays'].notna()]
x = sdf['SleepHoursWeekdaysOrWorkdays']
n = len(x)
mu_hat = x.mean()
print(f'n = {n}, mu_hat = {mu_hat:.4f}')

n = 5489, mu_hat = 7.6212

In [12]:
np.random.seed(1)
R = 2_000
results = []
for t in range(R):
    idx = np.random.randint(0, n, n)
    results.append(x.iloc[idx].mean())
results = np.array(results)
print(f'seed = 1, R = {R}')

seed = 1, R = 2000

In [13]:
mu_0 = 8
se = np.std(results, ddof=1)
z = (mu_hat - mu_0) / se
p = 2 * norm.cdf(-np.abs(z))
row = {'variable': 'SleepHoursWeekdaysOrWorkdays', 'estimate': mu_hat, 'SE': se, 'z': z, 'p': p}
for conf, alpha in [(90, .10), (95, .05), (99, .01)]:
    c = norm.ppf(1 - alpha / 2)
    row[f'normal {conf}%'] = f'({mu_hat - c*se:.3f}, {mu_hat + c*se:.3f})'
    row[f'contains mu_0 {conf}%'] = mu_hat - c*se <= mu_0 <= mu_hat + c*se
row['significant at'] = ', '.join(f'{conf}%' for conf, alpha in [(90, .10), (95, .05), (99, .01)] if p < alpha) or 'none'

ci_table = pd.DataFrame([row]).set_index('variable')
ci_table.round(3)

,estimate,SE,z,p,normal 90%,contains mu_0 90%,normal 95%,contains mu_0 95%,normal 99%,contains mu_0 99%,significant at
variable,,,,,,,,,,,
SleepHoursWeekdaysOrWorkdays,7.621,0.023,-16.402,0.0,"(7.583, 7.659)",False,"(7.576, 7.667)",False,"(7.562, 7.681)",False,"90%, 95%, 99%"

Adults in our data on average sleep around 7.62 hours on weekdays. 8 hours is excluded from all three intervals and $p$ is close to 0, so we reject $H_0$ at 90, 95, and 99%.